-- Pottywipe 2019 Joseph DeCommer

CREATE TABLE pooquotes (
  ID SERIAL PRIMARY KEY,
  quote VARCHAR(255) NOT NULL
);

INSERT INTO pooquotes (quote) VALUES ('🎉 This is the first poo of the New Year!');
INSERT INTO pooquotes (quote) VALUES ('🥈 The number two poo');
INSERT INTO pooquotes (quote) VALUES ('My bowels rested on the 3rd day of the year, but not the 4th!');
INSERT INTO pooquotes (quote) VALUES ('I call this one "The Knot');
INSERT INTO pooquotes (quote) VALUES ('🤢 Disregard the hair. GROSS!');
INSERT INTO pooquotes (quote) VALUES ('The Murky deep.');
INSERT INTO pooquotes (quote) VALUES ('This poo broke up on contact.');
INSERT INTO pooquotes (quote) VALUES ('🥫 I don''t know why this one is so red. Ketchup perhaps?');
INSERT INTO pooquotes (quote) VALUES ('First of the many "goo" poos');
INSERT INTO pooquotes (quote) VALUES ('💥 Explosion!');
INSERT INTO pooquotes (quote) VALUES ('🌽 Hey corn!! It IS real!');
INSERT INTO pooquotes (quote) VALUES ('This turd is looking a little grey');
INSERT INTO pooquotes (quote) VALUES ('I like the ropiness of this one.');
INSERT INTO pooquotes (quote) VALUES ('Small and not too spectacular.');
INSERT INTO pooquotes (quote) VALUES ('It''s a poo!');
INSERT INTO pooquotes (quote) VALUES ('Lumpy in the front');
INSERT INTO pooquotes (quote) VALUES ('🦑 Pardon the dark appearance of this sea monster');
INSERT INTO pooquotes (quote) VALUES ('🏔 This one is a pretty big mound');
INSERT INTO pooquotes (quote) VALUES ('I was too concerned with wiping my butt to make a quote I guess');
INSERT INTO pooquotes (quote) VALUES ('Sooper loong!');
INSERT INTO pooquotes (quote) VALUES ('Nice coil to this one');
INSERT INTO pooquotes (quote) VALUES ('This girth is something to behold!');
INSERT INTO pooquotes (quote) VALUES ('The longest poo to close out January.');

INSERT INTO pooquotes (quote) VALUES ('This poo is ''uge''');
INSERT INTO pooquotes (quote) VALUES ('Gooey');
INSERT INTO pooquotes (quote) VALUES ('This one has length and girth, but fell apart');
INSERT INTO pooquotes (quote) VALUES ('🥨 Pretzel poo');
INSERT INTO pooquotes (quote) VALUES ('🔺 This one seems to have three ends... strange');
INSERT INTO pooquotes (quote) VALUES ('The lump');
INSERT INTO pooquotes (quote) VALUES ('🧬 This poo has a helix-like twist');
INSERT INTO pooquotes (quote) VALUES ('Forgot to take the poo picture. 🙄');
INSERT INTO pooquotes (quote) VALUES ('Pile with a pig tail poo');
INSERT INTO pooquotes (quote) VALUES ('Somewhere between solid and soft');
INSERT INTO pooquotes (quote) VALUES ('This poo piled out');
INSERT INTO pooquotes (quote) VALUES ('Poof. Liquid poo!');
INSERT INTO pooquotes (quote) VALUES ('🐍 Snake-like goo poo.');
INSERT INTO pooquotes (quote) VALUES ('Super long! And super straight!');
INSERT INTO pooquotes (quote) VALUES ('This poo started small, but grew up fast');
INSERT INTO pooquotes (quote) VALUES ('📀 Compact pile');

INSERT INTO pooquotes (quote) VALUES ('A very brown poo!');
INSERT INTO pooquotes (quote) VALUES ('Long, but not too long');
INSERT INTO pooquotes (quote) VALUES ('This one''s got the curl!');
INSERT INTO pooquotes (quote) VALUES ('Giant coil.');
INSERT INTO pooquotes (quote) VALUES ('🐍 Snake poo');
INSERT INTO pooquotes (quote) VALUES ('🎢 This poo has it all! Twists, turns, solid, goo');
INSERT INTO pooquotes (quote) VALUES ('Bulbous');
INSERT INTO pooquotes (quote) VALUES ('Perfect coiled, but blurry picture');
INSERT INTO pooquotes (quote) VALUES ('Your Sharona? My intestines.');
INSERT INTO pooquotes (quote) VALUES ('Long and strong');
INSERT INTO pooquotes (quote) VALUES ('🧻 TOILET PAPER NOOOOOO!');
INSERT INTO pooquotes (quote) VALUES ('🚰 Never mind the drip.');
INSERT INTO pooquotes (quote) VALUES ('🐣 Too much peeps, not enough poops');
INSERT INTO pooquotes (quote) VALUES ('✊ Fist in the air!');
INSERT INTO pooquotes (quote) VALUES ('💥 This is a dis-ass-ter. Nice poo though');
INSERT INTO pooquotes (quote) VALUES ('Heads or tails?');
INSERT INTO pooquotes (quote) VALUES ('Tall and blonde poo');
INSERT INTO pooquotes (quote) VALUES ('🌀Poo Spiral.');
INSERT INTO pooquotes (quote) VALUES ('🚮This one would be epic without the T.P.');

INSERT INTO pooquotes (quote) VALUES ('🤮 Goop');
INSERT INTO pooquotes (quote) VALUES ('A blurry pile with a T.P. top.');
INSERT INTO pooquotes (quote) VALUES ('🙅 Arms crossed.');
INSERT INTO pooquotes (quote) VALUES ('🐋 The beached whale.');
INSERT INTO pooquotes (quote) VALUES ('I have no idea what all that other stuff is..');
INSERT INTO pooquotes (quote) VALUES ('🧸 Make bears');
INSERT INTO pooquotes (quote) VALUES ('Curled up.');
INSERT INTO pooquotes (quote) VALUES ('The T.P. almost ruined this one!');
INSERT INTO pooquotes (quote) VALUES ('🐥 Peeps with poops');
INSERT INTO pooquotes (quote) VALUES ('Tight coil');
INSERT INTO pooquotes (quote) VALUES ('👀 Whoa');
INSERT INTO pooquotes (quote) VALUES ('French curve');
INSERT INTO pooquotes (quote) VALUES ('Damn');
INSERT INTO pooquotes (quote) VALUES ('🐩 Oodles of poo-dlesOodles of poo-dles');
INSERT INTO pooquotes (quote) VALUES ('🌑 Hiding in the dark');
INSERT INTO pooquotes (quote) VALUES ('Nice finish');
INSERT INTO pooquotes (quote) VALUES ('Came apart on exit.');
INSERT INTO pooquotes (quote) VALUES ('🚫 This one is just... no');
INSERT INTO pooquotes (quote) VALUES ('Barely worth a mention');
INSERT INTO pooquotes (quote) VALUES ('A strange little poo');
INSERT INTO pooquotes (quote) VALUES ('Dark brown and strong');
INSERT INTO pooquotes (quote) VALUES ('⛪ HOLY PILE!');
INSERT INTO pooquotes (quote) VALUES ('🤷 Where does it all come from!?');

INSERT INTO pooquotes (quote) VALUES ('Giant pile');
INSERT INTO pooquotes (quote) VALUES ('😎 This poo has a nice sheen');
INSERT INTO pooquotes (quote) VALUES ('Three point turd');
INSERT INTO pooquotes (quote) VALUES ('The poo pyramid');
INSERT INTO pooquotes (quote) VALUES ('Remnants');
INSERT INTO pooquotes (quote) VALUES ('🌥 cloud pile');
INSERT INTO pooquotes (quote) VALUES ('Mud lumps');
INSERT INTO pooquotes (quote) VALUES ('🤨 Some serious goo');
INSERT INTO pooquotes (quote) VALUES ('Turd water');
INSERT INTO pooquotes (quote) VALUES ('Warm goo');
INSERT INTO pooquotes (quote) VALUES ('☣ Sometimes poo looks like some kind of logo');
INSERT INTO pooquotes (quote) VALUES ('The blob.');
INSERT INTO pooquotes (quote) VALUES ('📀 Compact.');
INSERT INTO pooquotes (quote) VALUES ('😨 What the poo?!');
INSERT INTO pooquotes (quote) VALUES ('Return of the poo!');
INSERT INTO pooquotes (quote) VALUES ('Tiny');
INSERT INTO pooquotes (quote) VALUES ('Solid with the curls');
INSERT INTO pooquotes (quote) VALUES ('A gooey end.');
INSERT INTO pooquotes (quote) VALUES ('😎 This poo just looks cool');
INSERT INTO pooquotes (quote) VALUES ('⚓ Anchors away!');
INSERT INTO pooquotes (quote) VALUES ('🐶 Poo puppies!');
INSERT INTO pooquotes (quote) VALUES ('Fits a goo-type theme');
INSERT INTO pooquotes (quote) VALUES ('Plop');

INSERT INTO pooquotes (quote) VALUES ('Just firm enough to coil!');
INSERT INTO pooquotes (quote) VALUES ('💠 Shards');
INSERT INTO pooquotes (quote) VALUES ('🦷 I don''t know if that''s corn, or a tooth...');
INSERT INTO pooquotes (quote) VALUES ('⛰ Land slide');
INSERT INTO pooquotes (quote) VALUES ('🎨 Abstract shart!');
INSERT INTO pooquotes (quote) VALUES ('🦑 From the depths.');
INSERT INTO pooquotes (quote) VALUES ('🌏 This poo''s going in all directions');
INSERT INTO pooquotes (quote) VALUES ('🎢 Roller poopster');
INSERT INTO pooquotes (quote) VALUES ('🏃 Pre run poo');
INSERT INTO pooquotes (quote) VALUES ('🏃 Post run poo');
INSERT INTO pooquotes (quote) VALUES ('🌽 I really don''t eat this much corn');
INSERT INTO pooquotes (quote) VALUES ('Tied a knot in it.');
INSERT INTO pooquotes (quote) VALUES ('💣 Just when I think I wasn''t going to have to poop. BOOM');
INSERT INTO pooquotes (quote) VALUES ('🍕 Product of a whole large pizza.');
INSERT INTO pooquotes (quote) VALUES ('👹 One hell of a poo.');
INSERT INTO pooquotes (quote) VALUES ('🌯 Burrito!');
INSERT INTO pooquotes (quote) VALUES ('right down the middle... almost.');
INSERT INTO pooquotes (quote) VALUES ('🌽 I don''t know where all this corn is coming from.');
INSERT INTO pooquotes (quote) VALUES ('The poo just kept comin''.');
INSERT INTO pooquotes (quote) VALUES ('🤔 That''s deep!');
INSERT INTO pooquotes (quote) VALUES ('🐣 Peeps and poops!');
INSERT INTO pooquotes (quote) VALUES ('🐉 Toilet snake!');
INSERT INTO pooquotes (quote) VALUES ('Whew! That was a close one!');
INSERT INTO pooquotes (quote) VALUES ('Yesterday''s twin!');
INSERT INTO pooquotes (quote) VALUES ('🏖 Last poo of June! SUMMERTIME!!!');

INSERT INTO pooquotes (quote) VALUES ('🏄 Piling on the summer fun!');
INSERT INTO pooquotes (quote) VALUES ('July the TURD! This one looks like a figure 8!');
INSERT INTO pooquotes (quote) VALUES ('💥 🍖 PILE on the BBQ and explosions! It''s the fourth of Pooly!');
INSERT INTO pooquotes (quote) VALUES ('🇮🇹 Now that''s Italian');
INSERT INTO pooquotes (quote) VALUES ('🐢 A slow moving poo');
INSERT INTO pooquotes (quote) VALUES ('🌩 July 6th strikes again..');
INSERT INTO pooquotes (quote) VALUES ('🍘 Late night poo nugs!.');
INSERT INTO pooquotes (quote) VALUES ('👮 The long arm of the poo.');
INSERT INTO pooquotes (quote) VALUES ('🍮 Gooey and ...chewy? Gross');
INSERT INTO pooquotes (quote) VALUES ('🥀 This two goes out to all the mother-in-laws out there in poo land!');
INSERT INTO pooquotes (quote) VALUES ('🌳 Two poos in the hand is worth one poo in the bush.');
INSERT INTO pooquotes (quote) VALUES ('😵Quicksand! Lookout!!');
INSERT INTO pooquotes (quote) VALUES ('😳 Whoa big!');
INSERT INTO pooquotes (quote) VALUES ('Poo on top of poo!');
INSERT INTO pooquotes (quote) VALUES ('There is no hard and fast way to poo. Just poo hard and fast!');
INSERT INTO pooquotes (quote) VALUES ('Little late-night poo!');
INSERT INTO pooquotes (quote) VALUES ('...And the rest');
INSERT INTO pooquotes (quote) VALUES ('🕍 Holy crap!');
INSERT INTO pooquotes (quote) VALUES ('The poo just keeps-a-comin''!');
INSERT INTO pooquotes (quote) VALUES ('💪 Long and strong!');
INSERT INTO pooquotes (quote) VALUES ('Second poo of the day. I $%it you not...');
INSERT INTO pooquotes (quote) VALUES ('Poo me once shame on you. Poo me twice... Poo me... ? Poo me, won''t get pooed again!
-George ''double poo'' Bush.');
INSERT INTO pooquotes (quote) VALUES ('🎶 Ob-La-Di, ob-La-Da poo goes on!');
INSERT INTO pooquotes (quote) VALUES ('🛣 Travelling down the long and winding poo.');
INSERT INTO pooquotes (quote) VALUES ('🎟 I could have sold tickets to this poo!');
INSERT INTO pooquotes (quote) VALUES ('🐝 P out my B!');
INSERT INTO pooquotes (quote) VALUES ('🐲 The stuff of legend!');

INSERT INTO pooquotes (quote) VALUES ('🤖R-Poo-P-Poo');
INSERT INTO pooquotes (quote) VALUES ('The good the bad and the remnants.');
INSERT INTO pooquotes (quote) VALUES ('💢 This one has a strange configuration');
INSERT INTO pooquotes (quote) VALUES ('💩 August da turd');
INSERT INTO pooquotes (quote) VALUES ('💫 Poo: The real Never-Ending Story');
INSERT INTO pooquotes (quote) VALUES ('💩 There''s one in me; there''s one in you. Poo.');
INSERT INTO pooquotes (quote) VALUES ('🕵 Who let the poos out!');
INSERT INTO pooquotes (quote) VALUES ('This poo felt weak.');
INSERT INTO pooquotes (quote) VALUES ('🤧 Now that''s what I call a stinky situation!');
INSERT INTO pooquotes (quote) VALUES ('🤮 Repugnant!');
INSERT INTO pooquotes (quote) VALUES ('Never stop the poo!');
INSERT INTO pooquotes (quote) VALUES ('Well, the poo stopped for a little while');
INSERT INTO pooquotes (quote) VALUES ('🏢 Brown is in town!');
INSERT INTO pooquotes (quote) VALUES ('🔬 Eat less poo less. Science!');
INSERT INTO pooquotes (quote) VALUES ('🥪 Bologna sausage!');
INSERT INTO pooquotes (quote) VALUES ('🥤 My poopshake brings all the flies to the yard.');
INSERT INTO pooquotes (quote) VALUES ('🍫 Milk milk lemonade around the corner fudge is made!');
INSERT INTO pooquotes (quote) VALUES ('🍷 Not my finest...');
INSERT INTO pooquotes (quote) VALUES ('☕ Coffee was the catalyst!');
INSERT INTO pooquotes (quote) VALUES ('🚽 I think it''s time to clean the turlet!');
INSERT INTO pooquotes (quote) VALUES ('🧯 A whole can of poo spray!');
INSERT INTO pooquotes (quote) VALUES ('😖 Some poos have to be forced into the world.');
INSERT INTO pooquotes (quote) VALUES ('👖 If you wear pants made of crap, no one can tell if you crapped your pants.');
INSERT INTO pooquotes (quote) VALUES ('🥵 When it''s hot, poos get shot. ...out of your butt.');
INSERT INTO pooquotes (quote) VALUES ('📱 NO! I have never dropped my phone in the toilet...');
INSERT INTO pooquotes (quote) VALUES ('🍽 Eat poo repeat.');
INSERT INTO pooquotes (quote) VALUES ('🧫 Respect poo culture');
INSERT INTO pooquotes (quote) VALUES ('📃 The poo was due!');
INSERT INTO pooquotes (quote) VALUES ('🔕 Nothing to sound the poo alarm about!');
INSERT INTO pooquotes (quote) VALUES ('🌋 Sometimes poo flows like lava');
INSERT INTO pooquotes (quote) VALUES ('🇺🇸 America the pootiful');
INSERT INTO pooquotes (quote) VALUES ('⚰️ You haven''t lived until you''ve pooed!');
INSERT INTO pooquotes (quote) VALUES ('🍛 Indian food. ''Nuff said.');
INSERT INTO pooquotes (quote) VALUES ('✨ Over in a flash');
INSERT INTO pooquotes (quote) VALUES ('🧬 Poo! There''s DNA in it!');
INSERT INTO pooquotes (quote) VALUES ('🕹 Don''t let the poo control you. You control the poo.');
INSERT INTO pooquotes (quote) VALUES ('🍻 Poos and brews!');
INSERT INTO pooquotes (quote) VALUES ('🚓 Call the cops! My butt has committed a terrible crime!');
INSERT INTO pooquotes (quote) VALUES ('📰 Everyone reads on the can, right?');
INSERT INTO pooquotes (quote) VALUES ('⛽ Never out of gas!');
INSERT INTO pooquotes (quote) VALUES ('🦛 Go watch hippos fling their poo on YouTube. It''s cute.');